//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoanBroker.LoanRequestService1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LoanRequestService1.LoanRequestServiceSoap")]
    public interface LoanRequestServiceSoap {
        
        // CODEGEN: Generating message contract since element name SSN from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StartLoanRequest", ReplyAction="*")]
        LoanBroker.LoanRequestService1.StartLoanRequestResponse StartLoanRequest(LoanBroker.LoanRequestService1.StartLoanRequestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StartLoanRequest", ReplyAction="*")]
        System.Threading.Tasks.Task<LoanBroker.LoanRequestService1.StartLoanRequestResponse> StartLoanRequestAsync(LoanBroker.LoanRequestService1.StartLoanRequestRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StartLoanRequestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="StartLoanRequest", Namespace="http://tempuri.org/", Order=0)]
        public LoanBroker.LoanRequestService1.StartLoanRequestRequestBody Body;
        
        public StartLoanRequestRequest() {
        }
        
        public StartLoanRequestRequest(LoanBroker.LoanRequestService1.StartLoanRequestRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class StartLoanRequestRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double amount;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int lånetid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string SSN;
        
        public StartLoanRequestRequestBody() {
        }
        
        public StartLoanRequestRequestBody(double amount, int lånetid, string SSN) {
            this.amount = amount;
            this.lånetid = lånetid;
            this.SSN = SSN;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StartLoanRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="StartLoanRequestResponse", Namespace="http://tempuri.org/", Order=0)]
        public LoanBroker.LoanRequestService1.StartLoanRequestResponseBody Body;
        
        public StartLoanRequestResponse() {
        }
        
        public StartLoanRequestResponse(LoanBroker.LoanRequestService1.StartLoanRequestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class StartLoanRequestResponseBody {
        
        public StartLoanRequestResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LoanRequestServiceSoapChannel : LoanBroker.LoanRequestService1.LoanRequestServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoanRequestServiceSoapClient : System.ServiceModel.ClientBase<LoanBroker.LoanRequestService1.LoanRequestServiceSoap>, LoanBroker.LoanRequestService1.LoanRequestServiceSoap {
        
        public LoanRequestServiceSoapClient() {
        }
        
        public LoanRequestServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LoanRequestServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoanRequestServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoanRequestServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LoanBroker.LoanRequestService1.StartLoanRequestResponse LoanBroker.LoanRequestService1.LoanRequestServiceSoap.StartLoanRequest(LoanBroker.LoanRequestService1.StartLoanRequestRequest request) {
            return base.Channel.StartLoanRequest(request);
        }
        
        public void StartLoanRequest(double amount, int lånetid, string SSN) {
            LoanBroker.LoanRequestService1.StartLoanRequestRequest inValue = new LoanBroker.LoanRequestService1.StartLoanRequestRequest();
            inValue.Body = new LoanBroker.LoanRequestService1.StartLoanRequestRequestBody();
            inValue.Body.amount = amount;
            inValue.Body.lånetid = lånetid;
            inValue.Body.SSN = SSN;
            LoanBroker.LoanRequestService1.StartLoanRequestResponse retVal = ((LoanBroker.LoanRequestService1.LoanRequestServiceSoap)(this)).StartLoanRequest(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LoanBroker.LoanRequestService1.StartLoanRequestResponse> LoanBroker.LoanRequestService1.LoanRequestServiceSoap.StartLoanRequestAsync(LoanBroker.LoanRequestService1.StartLoanRequestRequest request) {
            return base.Channel.StartLoanRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<LoanBroker.LoanRequestService1.StartLoanRequestResponse> StartLoanRequestAsync(double amount, int lånetid, string SSN) {
            LoanBroker.LoanRequestService1.StartLoanRequestRequest inValue = new LoanBroker.LoanRequestService1.StartLoanRequestRequest();
            inValue.Body = new LoanBroker.LoanRequestService1.StartLoanRequestRequestBody();
            inValue.Body.amount = amount;
            inValue.Body.lånetid = lånetid;
            inValue.Body.SSN = SSN;
            return ((LoanBroker.LoanRequestService1.LoanRequestServiceSoap)(this)).StartLoanRequestAsync(inValue);
        }
    }
}
